# Generated by Django 3.0.4 on 2020-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AddField(
            model_name='link',
            name='aid',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
