# Generated by Django 3.0.4 on 2020-05-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20200521_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='aid',
        ),
        migrations.AddField(
            model_name='link',
            name='auto_increment_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
